name: Build and Deploy
on:
  push:
    branches:
      - main  # Setze den Namen deines Haupt-Branches hier ein
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Stelle sicher, dass du die Version spezifizierst, die du verwendest

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Stelle sicher, dass dieser Pfad zum Output deines Build-Prozesses passt
